# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
#  release:
#    types: [published]
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.craftex.dev
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
        with:
          path: "frontend"
          
      - name: Authentication MonkaW
        env:
          REGISTRY_PASSWORD: ${{ env.REGISTRY_PASSWORD }}
        run: |
          echo ${{ env.REGISTRY }}
          echo ${{ env.REGISTRY_PASSWORD }}
          echo $REGISTRY_PASSWORD
          echo $secrets.DOCKER_PASSWORD
          echo ${{ secrets.DOCKER_PASSWORD }}
          echo $REGISTRY_PASSWORD | docker login -u "github_workflow" --password-stdin

  update_ssh_linode:
    name: Linode Update
    needs: "build-and-push-image"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash update.sh
