name: Publish Release

on:
  release:
    types: [published]
  push:
    branches: [docker]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REPOSITORY: ${{ github.event.repository.name }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: releases
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: xrexy/events-fork
          excludes: "draft"

      - name: Authenticate MonkaW
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin

      - name: Build 💅
        env:
          PREFIX: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          VERSION: ${{ steps.releases.outputs.release }}
          API_ROUTE: ${{ secrets.API_ROUTE }}
        run: |
          echo $API_ROUTE > ./frontend/.env
          docker build ./frontend/ -t $PREFIX/frontend:$VERSION -t $PREFIX/frontend:latest
          docker build ./backend/ -t $PREFIX/backend:$VERSION -t $PREFIX/backend:latest

      - name: Push 😰
        run: |
          docker push $REGISTRY/$REPOSITORY/backend --all-tags
          docker push $REGISTRY/$REPOSITORY/frontend --all-tags

      - name: Execute update script
        uses: appleboy/ssh-action@master
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_POT: ${{ secrets.SSH_PORT }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: bash ~/prod/update -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }} -r ${{ env.REGISTRY }} -f ${{ env.REPOSITORY }}
