name: Publish Release

on:
#  release:
#    types: [published]
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.craftex.dev
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_POT: ${{ secrets.SSH_PORT }}

jobs:
  prep-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
          
      - name: Authenticate MonkaW
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin
        
      - name: Compose 💅
        run: docker-compose up -d
        
      - name: Tag Images 🥸
        env:
          BASE: events-fork
        run: |
          docker image list
          docker image tag $BASE/backend $REGISTRY/$BASE/backend
          docker image tag $BASE/frontend $REGISTRY/$BASE/frontend
          
      - name: Push 😰
        env:
          BASE: events-fork
        run: |
          docker push $REGISTRY/$BASE/backend:latest
          docker push $REGISTRY/$BASE/frontend:latest

  update_images:
    name: Linode Update
    needs: "prep-images"
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote update script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls
            echo "hey" > test.txt
            bash docker_update.sh
