# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
#  release:
#    types: [published]
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.craftex.dev
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
        with:
          path: "frontend"
          
      - name: Authenticate MonkaW
        env:
          PASSWORD: ${{ env.REGISTRY_PASSWORD }}
          USERNAME: ${{ env.REGISTRY_USERNAME }}
        run: echo $PASSWORD | docker login $REGISTRY -u $USERNAME --password-stdin
        
      - name: Compose 💅
        run: docker-compose up
        
      - name: Tag Images 🥸
        env:
          BASE: events-fork
        run: |
          docker image tag $BASE/backend $REGISTRY/$BASE/backend:latest
          docker image tag $BASE/frontend $REGISTRY/$BASE/frontend:latest
          
      - name: Push 😰
        env:
          BASE: events-fork
        run: |
          docker push $REGISTRY/$BASE/backend:latest
          docker push $REGISTRY/$BASE/frontend:latest

  update_ssh_linode:
    name: Linode Update
    needs: "build-and-push-image"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash update.sh
