name: Publish Release

on:
  release:
    types: [published]
  push:
    branches: [ "docker" ]

env:
  REGISTRY: registry.craftex.dev
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_POT: ${{ secrets.SSH_PORT }}
  BASE: events-fork

jobs:
  prep-images:
    needs: [update_images]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
          
      - name: Authenticate MonkaW
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin
        
      - name: Build 💅
        run: |
          echo ${{ github.repository }}
          docker build ./frontend/ -t $REGISTRY/$BASE/frontend:latest
          docker build ./backend/ -t $REGISTRY/$BASE/backend:latest
          
      - name: Push 😰
        run: |
          docker push $REGISTRY/$BASE/backend:latest
          docker push $REGISTRY/$BASE/frontend:latest

  update_images:
    name: Linode Update
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote update script
        uses: appleboy/ssh-action@master
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ github.repository }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo $REPOSITORY > repo.txt
            echo $REGISTRY > reg.txt
            bash ~/prod/update -r "$REGISTRY" -p events-fork -t latest
