name: Publish Release

on:
  release:
    types: [published]
  push:
    branches: [ "docker" ]

env:
  REGISTRY: registry.craftex.dev
  BASE: events-fork
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
          
      - name: Authenticate MonkaW
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin
        
      - name: Build 💅
        run: |
          echo ${{ github.repository }}
          docker build ./frontend/ -t $REGISTRY/$BASE/frontend:latest
          docker build ./backend/ -t $REGISTRY/$BASE/backend:latest
          
      - name: Push 😰
        run: |
          docker push $REGISTRY/$BASE/backend:latest
          docker push $REGISTRY/$BASE/frontend:latest

      - name: Get Latest Release
        id: releases
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: xrexy/events-fork
          excludes: "prerelease, draft"
          
      - name: Execute update script
        uses: appleboy/ssh-action@master
        env:
          PREFIX: ${{ github.event.repository.name }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_POT: ${{ secrets.SSH_PORT }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash ~/prod/update -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }} -r ${{ env.REGISTRY }} -f ${{ env.PREFIX }} -t latest
            echo ${{ steps.releases.outputs.release }} > release
