name: Publish Release

on:
#  release:
#    types: [published]
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.craftex.dev
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  prep-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout >w>
        uses: actions/checkout@v2
          
      - name: Authenticate MonkaW
        env:
          PASSWORD: ${{ env.REGISTRY_PASSWORD }}
          USERNAME: ${{ env.REGISTRY_USERNAME }}
        run: echo $PASSWORD | docker login $REGISTRY -u $USERNAME --password-stdin
        
      - name: Compose 💅
        run: docker-compose up -d
        
      - name: Tag Images 🥸
        env:
          BASE: events-fork
        run: |
          docker image list
          docker image tag $BASE/backend $REGISTRY/$BASE/backend
          docker image tag $BASE/frontend $REGISTRY/$BASE/frontend
          
      - name: Push 😰
        env:
          BASE: events-fork
        run: |
          docker push $REGISTRY/$BASE/backend:latest
          docker push $REGISTRY/$BASE/frontend:latest

  update_ssh_linode:
    name: Linode Update
    needs: "prep-images"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: bash update.sh
